# Generated by Django 3.1.6 on 2021-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='tull@epost.com', max_length=100),
            preserve_default=False,
        ),
    ]
