# Generated by Django 3.1.6 on 2021-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=63.446827, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=10.421906, max_digits=9),
        ),
    ]
