# Generated by Django 3.1.6 on 2021-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210216_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
