# Generated by Django 3.1.6 on 2021-03-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210325_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='savedAd',
        ),
    ]
