# Generated by Django 3.1.6 on 2021-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210216_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_location',
            field=models.CharField(default='', max_length=20),
        ),
    ]
