# Generated by Django 3.1.6 on 2021-04-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_feedback_recipient'),
        ('profiles', '0009_profile_reklame_limit'),
    ]

    operations = [
    ]
