# Generated by Django 3.1.6 on 2021-02-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=63.446827, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=10.421906, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.location'),
        ),
    ]
