# Generated by Django 3.1.6 on 2021-02-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_remove_advertisement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.location'),
        ),
    ]
