# Generated by Django 3.1.6 on 2021-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_advertisement_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='location',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=63.446827, max_digits=9),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=10.421906, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
