# Generated by Django 3.1.6 on 2021-03-26 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0010_usersavedad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersavedad',
            unique_together={('user', 'ad')},
        ),
    ]
