# Generated by Django 3.1.6 on 2021-04-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0008_profile_is_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=64)),
                ('banner', models.ImageField(upload_to='images/reklame')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('advertiser', models.ForeignKey(limit_choices_to=models.Q(is_advertiser=True), on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
