# Generated by Django 3.1.6 on 2021-04-03 08:42

from django.db import migrations, models
import reklame.models


class Migration(migrations.Migration):

    dependencies = [
        ('reklame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklame',
            name='expired',
            field=models.DateTimeField(default=reklame.models.one_week_hence),
        ),
    ]
