# Generated by Django 3.1.6 on 2021-04-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_reklame_limit'),
        ('reklame', '0003_requesttobeadvertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttobeadvertiser',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', unique=True),
        ),
    ]
