# Generated by Django 3.1.6 on 2021-04-04 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_reklame_limit'),
        ('reklame', '0004_auto_20210403_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToRenewAbonement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', unique=True)),
            ],
        ),
    ]
